# Site settings
title: "Agnese Chiatti"
description: "Agnese Chiatti's Webpage"
url: 'https://achiatti.github.io'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/background.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '4a93e3e01d.js'

author:
  name: 'Agnese Chiatti'
  email: agnese.chiatti@open.ac.uk
  twitter_username: agnese_chiatti
  github_username:  achiatti
  linkedin_username:  agnese-chiatti-44534a12a
  gscholar_name: iZnvJsMAAAAJ&hl

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed
plugins: 
- jekyll-sitemap
- jekyll-seo-tag

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md']



